### ISSUE TITLE
Checkpoint feature support

### ISSUE THREAD

**Issue by g3gurung** [vcabbage/amqp#1]
Is there the offset checkpoint(commit) feature supported yet?

**Comment by vcabbage** [comment]
I assume you're referring to checkpointing in Event Hubs, let me know if that's not correct. I'm not currently using Event Hubs so I haven't spent a lot of time looking into it. My cursory investigation suggests checkpointing is saving the current offset and using that on reconnect. According to https://stackoverflow.com/a/35470672/7102681, the offset is saved in Azure Storage and is not directly tied to Event Hubs or AMQP.

To deal with offsets this library minimally need to expose a way to set source filters. (Specifically `x-opt-offset`, documented here: http://azure.github.io/amqpnetlite/articles/azure_eventhubs.html) While this is not currently available in the API I believe it would be relatively easy to implement as a Link Option.

The offset of each message _should_ already be available in [`Message.Annotations`](https://godoc.org/pack.ag/amqp#Message.Annotations).

This library is focussed on the low-level AMQP 1.0 implementation. I have considered writing a higher level library specific to Event Hubs to handle these sort of details in a nicer way, but not likely to be a near-term project for me.

With filters exposed, consumers of this library would be able to implement checkpointing themselves. I'll look into the filter implementation this week.

**Comment by vcabbage** [comment]
Setting source filters is no supported in [v0.3.0](https://github.com/vcabbage/amqp/releases/tag/v0.3.0). This won't store the offset but it allows folks to build that into their applications or higher level libraries.

I'm going to go ahead and close this issue as the AMQP-level support is now available. Feel free to re-open if there are any problems with the filters.
