### ISSUE TITLE
zero idle time out not work as expected

### ISSUE THREAD

**Issue by emmansun** [vcabbage/amqp#100]
**conn.go** line 434  `_ = c.net.SetReadDeadline(time.Now().Add(c.idleTimeout))` , 

should change it to 

`			if c.idleTimeout > 0 {
				_ = c.net.SetReadDeadline(time.Now().Add(c.idleTimeout))
			}`

**Comment by vcabbage** [comment]
Thanks for reporting this!

I'll fix it this evening unless you'd like to send a PR.
