### ISSUE TITLE
Multiple consumers where "some of them are same"

### ISSUE THREAD

**Issue by surajssd** [vcabbage/amqp#101]
I have a service which has two instances `v1` and `v2`. Now since it's the same service with two different instances, what I would like to achieve is that both load balance on the queue they are subscribed to.

For e.g. if the queue has messages `1, 2, 3, 4, 5, ...`

the queues should get following in the order of

`v1 -> 1, 3, 5, ...`
`v2 -> 2, 4, ...`

Now if the `v2` instance goes down and isn't available any more then `v1` should start getting the following messages.

if the state of queue is `..., 12, 13, 14, 15, 16, ...` when message `14` arrives on queue and `v2` has failed.

`v1 -> .., 13, 14, 15, 16, ...`
`v2 -> 12, xxx`

How do I achieve this with this library? So from the documentation what I have learnt is that you can achieve this with something called [message grouping](https://activemq.apache.org/artemis/docs/latest/message-grouping.html).

I have tried multiple things like `amqp.LinkSessionFilter`, `amqp.LinkProperty`, `amqp.ConnProperty`, etc.

What is the right way to achieve this, any help and pointers will be helpful.

**Comment by vcabbage** [comment]
Hi,

I believe this is the default behavior of a queue (http://activemq.apache.org/how-does-a-queue-compare-to-a-topic.html). To my knowledge it shouldn't require any special configuration on the client side other than connecting to the queue.

Can you describe what you've tried and what didn't work?

**Comment by surajssd** [comment]
@vcabbage I have run this sender code once, https://github.com/surajssd/amqptests/blob/master/test2/sender/sender.go and this receiver code https://github.com/surajssd/amqptests/blob/master/test2/receiver/receiver.go twice!

**Comment by surajssd** [comment]
I am subscribed to the same queue in all of the code!

**Comment by vcabbage** [comment]
* What broker are you using? You previously linked to ActiveMQ documentation but this repo has references to RabbitMQ.
* How is your broker configured?
* What, in detail, happens when you run the code?

**Comment by surajssd** [comment]
> What broker are you using? You previously linked to ActiveMQ documentation but this repo has references to RabbitMQ.
> How is your broker configured?

So I have a deployment of ActiveMQ on Kubernetes done using a project called [enmasse](https://github.com/EnMasseProject/enmasse)(Qpid Dispatch Router network and Apache ActiveMQ broker).

The references to RabbitMQ were wrongly done(the name was wrongly put, there was no RabbitMQ used though).

> What, in detail, happens when you run the code?

Apart from the activemq deployment, I am also deploying the code of sender and reciever on Kubernetes, and it looks like this:

```console
$ kubectl get pods
NAME                         READY     STATUS    RESTARTS   AGE
receiver1-6758ddbb89-v2brs   1/1       Running   0          3m
receiver2-5fd5ffc7b8-kqgbx   1/1       Running   0          3m
receiver2-5fd5ffc7b8-l77sg   1/1       Running   0          3m
sender-589567d4b8-qz6p8      1/1       Running   0          3m
```

One instance of `receiver1`, 2 instances of `receiver2`.

These are sender logs:

```console
$ kubectl logs sender-589567d4b8-qz6p8
2018/06/04 09:15:00 [*] sent message: hello from "sender" on "sender-589567d4b8-qz6p8"! 0
2018/06/04 09:15:02 [*] sent message: hello from "sender" on "sender-589567d4b8-qz6p8"! 1
2018/06/04 09:15:04 [*] sent message: hello from "sender" on "sender-589567d4b8-qz6p8"! 2
2018/06/04 09:15:06 [*] sent message: hello from "sender" on "sender-589567d4b8-qz6p8"! 3
2018/06/04 09:15:08 [*] sent message: hello from "sender" on "sender-589567d4b8-qz6p8"! 4
2018/06/04 09:15:10 [*] sent message: hello from "sender" on "sender-589567d4b8-qz6p8"! 5
```

Now what I want is that `receiver2`'s two instances `receiver2-5fd5ffc7b8-kqgbx` and `receiver2-5fd5ffc7b8-l77sg` should load balance on the messages that are sent on the queue.

One instance of `receiver2` got this:

```console
$ kubectl logs receiver2-5fd5ffc7b8-kqgbx
2018/06/04 09:15:01 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-kqgbx": hello from "sender" on "sender-589567d4b8-qz6p8"! 0
2018/06/04 09:15:03 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-kqgbx": hello from "sender" on "sender-589567d4b8-qz6p8"! 1
2018/06/04 09:15:04 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-kqgbx": hello from "sender" on "sender-589567d4b8-qz6p8"! 2
2018/06/04 09:15:06 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-kqgbx": hello from "sender" on "sender-589567d4b8-qz6p8"! 3
2018/06/04 09:15:08 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-kqgbx": hello from "sender" on "sender-589567d4b8-qz6p8"! 4
2018/06/04 09:15:10 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-kqgbx": hello from "sender" on "sender-589567d4b8-qz6p8"! 5
2018/06/04 09:15:13 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-kqgbx": hello from "sender" on "sender-589567d4b8-qz6p8"! 6
2018/06/04 09:15:14 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-kqgbx": hello from "sender" on "sender-589567d4b8-qz6p8"! 7
2018/06/04 09:15:16 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-kqgbx": hello from "sender" on "sender-589567d4b8-qz6p8"! 8
```

and another instance also got all the same messages.

```console
$ kubectl logs receiver2-5fd5ffc7b8-l77sg
2018/06/04 09:15:03 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-l77sg": hello from "sender" on "sender-589567d4b8-qz6p8"! 1
2018/06/04 09:15:04 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-l77sg": hello from "sender" on "sender-589567d4b8-qz6p8"! 2
2018/06/04 09:15:06 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-l77sg": hello from "sender" on "sender-589567d4b8-qz6p8"! 3
2018/06/04 09:15:08 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-l77sg": hello from "sender" on "sender-589567d4b8-qz6p8"! 4
2018/06/04 09:15:10 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-l77sg": hello from "sender" on "sender-589567d4b8-qz6p8"! 5
2018/06/04 09:15:13 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-l77sg": hello from "sender" on "sender-589567d4b8-qz6p8"! 6
2018/06/04 09:15:14 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-l77sg": hello from "sender" on "sender-589567d4b8-qz6p8"! 7
2018/06/04 09:15:16 [*] message received on "receiver2" on "receiver2-5fd5ffc7b8-l77sg": hello from "sender" on "sender-589567d4b8-qz6p8"! 8
```

Why do I two instances of same service? For the purposes of scaling.

Now how do I make them load balance the messages, because if both of them are getting the same message then they both will act on it and do the task twice?

**Comment by vcabbage** [comment]
When I attempt to reproduce this with plain ActiveMQ it works as expected. The best advice I can give you at this point is to check the broker to make sure that these are showing up as queues and not topics. I'm not familiar with enmasse, but plain ActiveMQ has a web interface that shows this information.

These are the steps I took:

* Started a docker container with ActiveMQ: `docker run -p 61616:61616 -p 8161:8161 -p 5672:5672 --rm -it rmohr/activemq`
* Cloned your amqptests repo.
* Modified `commons/commons.go` to add the `amqp.ConnSASLAnonymous()` option to `amqp.Dial`.
* Ran two instances of `test2/receiver/receiver.go` in separate terminal windows.
* Ran one instance of `test2/sender/sender.go`.

Sender 1:

```
# go run sender.go
2018/06/04 06:44:27 [*] sent message: hello from "" on ""! 0
2018/06/04 06:44:29 [*] sent message: hello from "" on ""! 1
2018/06/04 06:44:31 [*] sent message: hello from "" on ""! 2
2018/06/04 06:44:33 [*] sent message: hello from "" on ""! 3
2018/06/04 06:44:35 [*] sent message: hello from "" on ""! 4
2018/06/04 06:44:37 [*] sent message: hello from "" on ""! 5
2018/06/04 06:44:39 [*] sent message: hello from "" on ""! 6
2018/06/04 06:44:41 [*] sent message: hello from "" on ""! 7
2018/06/04 06:44:43 [*] sent message: hello from "" on ""! 8
```

Receiver 1:

```
# go run receiver.go
2018/06/04 06:44:27 [*] message received on "" on "": hello from "" on ""! 0
2018/06/04 06:44:31 [*] message received on "" on "": hello from "" on ""! 2
2018/06/04 06:44:35 [*] message received on "" on "": hello from "" on ""! 4
2018/06/04 06:44:39 [*] message received on "" on "": hello from "" on ""! 6
2018/06/04 06:44:43 [*] message received on "" on "": hello from "" on ""! 8
```

Receiver 2:
```
# go run receiver.go
2018/06/04 06:44:29 [*] message received on "" on "": hello from "" on ""! 1
2018/06/04 06:44:33 [*] message received on "" on "": hello from "" on ""! 3
2018/06/04 06:44:37 [*] message received on "" on "": hello from "" on ""! 5
2018/06/04 06:44:41 [*] message received on "" on "": hello from "" on ""! 7
```

**Comment by surajssd** [comment]
@vcabbage thanks for the explanation, i will try this, I am sure the library does that automatically need to see what is wrong on the server side.
