### ISSUE TITLE
Does not handle Offered-Capabilities field in Open performative from AMQ7

### ISSUE THREAD

**Issue by ewk-elwa** [vcabbage/amqp#104]
The AMQPv1.0 spec section 2.7.1 indicates Offered-Capabilities is a list, however, when attempting to connect to AMQ7 Interconnect Router, the field arrives from AMQ7 router as 0xa3. The code attempts to read an ArrayHeader and fails.

Per the spec. I expected a list/array, which would mean the code is correct.
Per the AMQ7 Interconnect Router behavior I expect the Offered-Capabilities to be a symbol which the code does not handle.

I changed my local copy to expect symbol for offered-capabilities, and it works with AMQ7 Interconnect Router.

This might be a bug in AMQ7, not your code. I haven't try this with any other AMQPv1.0 deices.

**Comment by ewk-elwa** [comment]
Attached is a wireshark trace. The code fails when process packet 17 when expecting an ArraySymbol.

[ir-consumer4.pcap.zip](https://github.com/vcabbage/amqp/files/2109777/ir-consumer4.pcap.zip)

**Comment by vcabbage** [comment]
Thanks for reporting this!

It looks like an oversight on my part. That field should allow a single element or an array. I'll look into fixing it.

From the spec:
>The multiple attribute of a field description controls whether multiple element values are permitted in the representation. A single element of the type specified in the field description is always permitted. Multiple values are represented by the use of an array where the type of the elements in the array is the type defined in the field definition. Note that a null value and a zero-length array (with a correct type for its elements) both describe an absence of a value and MUST be treated as semantically identical.
http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-types-v1.0-os.html#section-composite-type-representation

**Comment by vcabbage** [comment]
I created #105. I'm not familiar with AMQ7, would you mind testing the fix and letting me know whether it corrects your issue?

**Comment by ewk-elwa** [comment]
Cool. Your fix worked perfectly in my AMQ7 test.
Thanks.
-Edward

**Comment by vcabbage** [comment]
Merged and tagged as a new release. Thanks for verifying it.
