### ISSUE TITLE
Properly handle buffered messages when a link is closed

### ISSUE THREAD

**Issue by vcabbage** [vcabbage/amqp#110]
If there are buffered messages when a link is closed a receiver may get the message or it may get the link error because:

> If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform pseudo-random selection.

https://golang.org/ref/spec#Select_statements

https://github.com/vcabbage/amqp/blob/e6aeb3d8e5ac68426935114ac2a430c32391e5a7/client.go#L1552-L1561

**Comment by vcabbage** [comment]
@alanconway I'm not following, in this library it is possible for `l.link.done` to be closed while there are pending messages buffered in `r.link.messages`.

**Comment by alanconway** [comment]
On Wed, Jul 4, 2018 at 2:40 PM, Kale Blankenship <notifications@github.com>
wrote:

> @alanconway <https://github.com/alanconway> I'm not following, in this
> library it is possible for l.link.done to be closed while there are
> pending messages buffered in r.link.messages.
>
Ah sorry - I was talking about my example based on the
qpid.apache.org/electron package. What purpose does l.link.done serve in
vcabbage if it is not indicating that the link is no longer useful?

From a protocol perspective links are serialized. Once a detach frame
arrives, there can't be any more deliveries on that link. I think it makes
sense to reflect that in the API - deliver the detach (however the API
indicates that, in this case closing a channel) *after* the messages. You
wouldn't re-order messages on a link, so why would you re-order the detach
by delivering it ahead of messages that arrived before it? I'm missing
something.

**Comment by vcabbage** [comment]
This is all internal to the library, not exposed to the user. `l.link.done` indicates that you can't perform any additional operations on the link. In the case of the receiver, there can still be received messages in the buffer. I think you're getting at the reason I created this bug, buffered messages should be delivered before returning the link error.

**Comment by alanconway** [comment]
On Wed, Jul 4, 2018 at 3:17 PM, Kale Blankenship <notifications@github.com>
wrote:

> This is all internal to the library, not exposed to the user. l.link.done
> indicates that you can't perform any additional operations on the link. In
> the case of the receiver, there can still be received messages in the
> buffer. I think you're getting at the reason I created this bug, buffered
> messages should be delivered before returning the link error.
>

Talking at cross purposes, sorry! Carry on :)
