### ISSUE TITLE
Add failover support

### ISSUE THREAD

**Issue by dambrisco** [vcabbage/amqp#111]
It would be extremely useful to have failover support included in this library, either in the form of JMS-style URLs (e.g. `"failover:(amqp://host1:5672,amqp://host2:5672)"`) or a connection option to provide secondary server URIs. Amazon's MQ product provides the former as a copy-paste option, but I'm not sure that that's a particularly compelling reason to prefer that over the latter.

**Comment by vcabbage** [comment]
I'm not sure directly handling failover logic fits well with this library's intent to be a low-level. I would imagine different scenarios call for different failover (and failback) approaches. I wonder if this could be supported via the link recovery API proposed in #109.

**Comment by dambrisco** [comment]
I was under the impression that failover was part of the AMQP 1.0 spec per https://www.oasis-open.org/committees/download.php/60517/amqp-failover-v1.0-wd02.pdf but I've just noticed that that's only a working draft and the complete 1.0 doc found here http://docs.oasis-open.org/amqp/core/v1.0/amqp-core-complete-v1.0.pdf doesn't reference failover at all.

Link recovery would probably be perfectly suited to handle this.
