### ISSUE TITLE
Method to update 'ContainerId' in 'performOpen' at start

### ISSUE THREAD

**Issue by vinithadinesh** [vcabbage/amqp#116]
Hi,
   Thanks for AMQP1.0 library. 
   I am able to communicate with RabbitMQ, however I am looking for a methods to update field ContainerID when the connection is open.
   Please advice on implementing a method or using existing method.

With thanks
Vinitha

**Comment by vcabbage** [comment]
The container ID is currently randomly generated. I'm happy to add an option to explicitly configure it if needed.

I'm not very familiar with the RabbitMQ implementation, does it use the container ID for some particular purpose?

Thanks

**Comment by vinithadinesh** [comment]
I am currently testing my communication with RabbitMQ, however the actual server implementation is designed to handle messages from different clients based on the Container ID.
It will be useful if you may provide the option of configuring Container ID. Highly appreciate your contribution.
Thanks for replying.

**Comment by vcabbage** [comment]
I added [`ConnContainerID`](https://godoc.org/pack.ag/amqp#ConnContainerID) to allow this. Please let me know if that adequately resolves the issue.

**Comment by vinithadinesh** [comment]
Thanks for updating the source.

I pass the "Container ID" when connection request is made, as below:

`client,` err := amqp.Dial("amqp://guest:guest@localhost:5672/", [`amqp.ConnContainerID("my.Machine.1"))`]
![cfx message](https://user-images.githubusercontent.com/34458678/43541024-35cef7e2-957e-11e8-8e42-00b829b2980e.png)


What I find is that the Dial function is not copying my container ID to the `conn` struct. when calling the function `newConn`. Hence the container ID is not passed in the frame.

Attached the screenshot for your reference. Please let me know if I am missing something.

Thanks
Vinitha

**Comment by vcabbage** [comment]
Thanks for confirming
