### ISSUE TITLE
Support for topics (publish to multiple consumers)

### ISSUE THREAD

**Issue by the-gigi** [vcabbage/amqp#121]
First, kudos on this project. I was able to connect to AWS MQ broker and write a producer + 2 consumers very quickly.

Currently when a sender sends a message to a queue with multiple receivers, just one receiver will receive the message. It would be very useful to add support for topics where all receivers listening on a topic will receive any message sent to this topic.

**Comment by vcabbage** [comment]
Hi,
Thanks for the kind words :)

Topic vs queue is ultimately up to the broker, this library should already support them. Each broker handles this a bit differently. From a brief reading, AWS MQ is based on ActiveMQ. I'm not deeply familiar with ActiveMQ, but it seems that the link source/target address should be prefixed with `topic://` for ActiveMQ. Have you tried that? If that doesn't work, can you provide some additional details on what you've tried?

**Comment by vcabbage** [comment]
I'm going to go ahead and close this issue. Feel free to reopen if necessary.
