### ISSUE TITLE
invalid frame body header

### ISSUE THREAD

**Issue by DingK-R** [vcabbage/amqp#123]
connect activemq has error.

in decode.go line 76

the peekFrameBodyType() 's payload is 

-------------------------------------------------------

iveMQ	�
                                        MaxFrameSize�������	CacheSize
                                                                         CacheEnabledSizePrefixDisabled MaxInactivityDurationInitalDelay'TcpNoDelayEnabled

-------------------------------------------------------

verification condition failed
payload[0] is 105
not 0

i don't know how to pass verification

**Comment by vcabbage** [comment]
If you'd like assistance I'll need to know what you're trying to do, what you tried, and what happened.

I'm closing this issue as it lacks useful information.

**Comment by quangtd95** [comment]
Hi Vcabbage, I'm also facing with this problem. When I connect to an ActiveMQ server, like this snippet: 
`tlsConfig := &tls.Config{
		RootCAs: caCertPool,
		Certificates:       []tls.Certificate{clientCert},
		InsecureSkipVerify: false,
	}
	client, errMQ := amqp.Dial(url,
		amqp.ConnSASLPlain(user, password),
		amqp.ConnTLSConfig(tlsConfig),
		amqp.ConnTLS(true),
		amqp.ConnServerHostname("kservproxyae.intranet-kbank.com"),
		)
	if errMQ != nil {
		golog.Error(errMQ)
		e = &mc
		return
	}`
and it throws an exception: invalid frame body header. I've taken a look in source code of this library and saw the exception from "the peekFrameBodyType()". same as DingK-R mentioned above. 
please give me a suggestion.
