### ISSUE TITLE
Accept() is not atomic

### ISSUE THREAD

**Issue by roidelapluie** [vcabbage/amqp#127]
When I create a Receiver with LinkCredit(10)
I read the first one, accept it,
then I stop and restart the app,
In that case the broker is sending me the first message again.

When  I wait for 10 messages
accept each of them
then I stop and restart the app,
In that case the broker is sending me the 11th message.

When I set Link Credit to 1 I do not have the problem.

**Comment by vcabbage** [comment]
Can you try with `amqp.LinkBatching(false)` added to the link options? This defaults to true with a 5 second timeout. 

Perhaps batching should be disabled by default since this behavior can be surprising.

**Comment by roidelapluie** [comment]
Thanks!!!

Adding to README is sufficient to me (#128)
