### ISSUE TITLE
Unable to specify Null as Session ID when applying Link Filter

### ISSUE THREAD

**Issue by marstr** [vcabbage/amqp#134]
Because a string is nullable in C#, the SDK allows for AMQP encoding of a string to either the string value or AMQP Null As seen here: 
[C# AMQP StringEncoding.cs#L30](https://github.com/Azure/azure-amqp/blob/1af9b1a1a9447da502ed84830bba7b436f5a7306/Microsoft.Azure.Amqp/Amqp/Encoding/StringEncoding.cs#L30)

At the moment, setting a session-filter does not allow for a nil value to be passed in:
https://github.com/vcabbage/amqp/blob/271d6282f59cd10184fef147de589cce8ad69c93/client.go#L1509

I'll have a PR in by EOD to change this.

**Comment by vcabbage** [comment]
Can you please describe the use case? The spec says that a null value is the same as not setting a filter.

**Comment by marstr** [comment]
> The spec says that a null value is the same as not setting a filter.

This is what I thought as well. However, as I've been implementing Service Bus support over here: https://github.com/marstr/azure-service-bus-go/tree/sessions I ran into a weird behavior. When I placed a session filter with a string value, the broker would pass me only messages with a particular `GroupID` (Service Bus calls this "SessionID" but I'll call it GroupID as AMQP does to avoid ambiguity) as expected. However, if I omit the filter, instead implicitly choosing a GroupID to filter on for me, it just sends messages from multiple session interleaved together. It's not clear to me, but I hope it would still at least assign an affinity between a particular GroupID and a particular link. When chatting with the Service Bus team about it, they said that the way to get my desired behavior and how to match the C# SDK was to provide a SessionFilter, but to have the ID be null. I checked against the C# SDK and [confirmed here](https://github.com/Azure/azure-service-bus-dotnet/blob/e5552e8cd2cb3072808ab306de164462bfd6c553/src/Microsoft.Azure.ServiceBus/SessionClient.cs#L267) that this is how the C# SDK does it.

**Comment by vcabbage** [comment]
I tried to find documentation on "com.microsoft:session-filter", but haven't had much luck. It makes me think we should revisit whether `LinkSessionFilter` really belongs in this library. Perhaps a different API for vendor specific filters is the better approach.

@devigned and I discussed this a bit previously when the option was added in https://github.com/vcabbage/amqp/pull/26

**Comment by marstr** [comment]
> It makes me think we should revisit whether LinkSessionFilter really belongs in this library. Perhaps a different API for vendor specific filters is the better approach.

Agreed, it doesn't feel like something that should live here to me. Given that `LinkOption` is an exported type, it would be just as easy for me to add the same method over in the service bus repository.

**Comment by marstr** [comment]
I can close out #135 if you'd like, or we can accept this PR for now and open an issue for me to refactor out the vendor specific stuff in the near future. Whichever you prefer is fine.

**Comment by marstr** [comment]
> Would modifying #135 to make an empty string indicate null work for the time being?

Let me do a little exploring to see if an empty string is a valid GroupID. If it's not valid, I don't mind that approach. If it is valid, I'm a little less comfortable with it, for fear that temporary work arounds often become permanent.

**Comment by marstr** [comment]
Looks like empty string is valid as a GroupID (for better or worse). 

I'll spend a few minutes tinkering to see if I can come up with something compelling for exposing these sorts of LinkOptions through third-party repositories.

**Comment by marstr** [comment]
I through-out another option, that isn't a breaking change but does expose through a little bit lower-level concept than previously shown. However, I think it's a good compromise and will allow me to write a method in Azure/azure-service-bus-go that does what I need for filtering.

**Comment by vcabbage** [comment]
> The spec says that a null value is the same as not setting a filter.

After rereading the spec, I realized my comment was incorrect, at least in this context.

The spec says:
>  Every key in the map MUST be of type symbol, every value MUST be either null or of a described type which provides the archetype filter. [...] If the value for a given key is null, this acts as if there were no such key present (i.e., all messages pass through the null filter).

In this case, it's setting the map value to a described type with a null value, which is subtly different.
