### ISSUE TITLE
Enable link source name & link source capabilities

### ISSUE THREAD

**Issue by haneev** [vcabbage/amqp#138]
In our company we would like to create a shared durable consumer. The *durable* part was solved with #133 (great work! :) thanks!) However, the shared part is not solved. For that to work we need be able to set a name on the source (`l.name`) and insert some capabilities (`l.source.Capabilities`). We are using ActiveMQ Artemis 2.5. And for that to work we needs to set a name, such that other applications can connect to the same name, and we also need to set the capability `shared` to tell that this queue is shared. 

I would propose a function called `LinkSourceName(name string)` to set/overwrite the name of the link object. (currently a random string of 40 is implemented). And to support capabilities i would like to introduce `LinkSourceCapabilities(capabilities ...symbol)`. 

I have already created code for this and tested it as well. Let me know what you think :) great project by the way.

https://github.com/vcabbage/amqp/compare/master...haneev:feature/shared-consumer?expand=1

**Comment by vcabbage** [comment]
Sounds good :+1: 

I have a few comments on the proposed changes, but please go ahead and open a PR.

**Comment by vcabbage** [comment]
I believe this is resolved. Feel free to re-open if there's anything else to be done.
