### ISSUE TITLE
Crashing due to high goroutine count

### ISSUE THREAD

**Issue by vinithadinesh** [vcabbage/amqp#146]
Hi,
  I am running my application with AMQP package on MIPS processor in an embedded system. It runs for 25 minutes and then crashes with the following message:

`goroutine 3981 [select, 25 minutes]:
pack.ag/amqp.(*link).mux(0x14515f0)
	/home/okiengg/go/src/pack.ag/amqp/client.go:991 +0x1b4
created by pack.ag/amqp.attachLink
	/home/okiengg/go/src/pack.ag/amqp/client.go:937 +0x4f4
`
The likely reason is its limited capacity to handle the number of routines AMQP package spawns.The same application runs without crashing on my laptop. 

Is there any way to added recover function to the package to automatically recover after a crash.

With thanks
Vinitha

**Comment by vcabbage** [comment]
Can you please post the full message? The cause of the crash should be at the very beginning. The line you provided only shows a single goroutine was blocking. For a single link there should only be around 5 goroutines created by this package.

**Comment by vinithadinesh** [comment]
Please find in the attached log.
`fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x25ba8a, 0x16)
	/usr/lib/go-1.11/src/runtime/panic.go:608 +0x60
runtime.sysMap(0x5400000, 0x400000, 0x3dbc98)
	/usr/lib/go-1.11/src/runtime/mem_linux.go:156 +0xf0
runtime.(*linearAlloc).alloc(0x3d00e4, 0x400000, 0x400000, 0x3dbc98, 0x0)
	/usr/lib/go-1.11/src/runtime/malloc.go:1230 +0xd0
runtime.(*mheap).sysAlloc(0x3cf620, 0x400000, 0x0, 0x37af4)
	/usr/lib/go-1.11/src/runtime/malloc.go:525 +0x78
runtime.(*mheap).grow(0x3cf620, 0x1, 0x0)
	/usr/lib/go-1.11/src/runtime/mheap.go:920 +0x4c
runtime.(*mheap).allocSpanLocked(0x3cf620, 0x1, 0x3dbca8, 0x5def0)
	/usr/lib/go-1.11/src/runtime/mheap.go:848 +0x3ac
runtime.(*mheap).alloc_m(0x3cf620, 0x1, 0x6, 0x0)
	/usr/lib/go-1.11/src/runtime/mheap.go:692 +0x14c
runtime.(*mheap).alloc.func1()
	/usr/lib/go-1.11/src/runtime/mheap.go:759 +0x5c
runtime.(*mheap).alloc(0x3cf620, 0x1, 0x10006, 0x0)
	/usr/lib/go-1.11/src/runtime/mheap.go:758 +0x90
runtime.(*mcentral).grow(0x3d0270, 0x0)
	/usr/lib/go-1.11/src/runtime/mcentral.go:232 +0xb8
runtime.(*mcentral).cacheSpan(0x3d0270, 0x73d74)
	/usr/lib/go-1.11/src/runtime/mcentral.go:106 +0x438
runtime.(*mcache).refill(0x77ee5000, 0xc76e06)
	/usr/lib/go-1.11/src/runtime/mcache.go:122 +0xb4
runtime.(*mcache).nextFree.func1()
	/usr/lib/go-1.11/src/runtime/malloc.go:749 +0x44
runtime.systemstack(0x73be0)
	/usr/lib/go-1.11/src/runtime/asm_mipsx.s:207 +0x9c
runtime.mstart()
	/usr/lib/go-1.11/src/runtime/proc.go:1229

goroutine 5 [running]:
runtime.systemstack_switch()
	/usr/lib/go-1.11/src/runtime/asm_mipsx.s:159 +0x8 fp=0xc76d3c sp=0xc76d38 pc=0x73cbc
runtime.(*mcache).nextFree(0x77ee5000, 0x53e8e06, 0x53e8e80, 0x36, 0x53e8ec0)
	/usr/lib/go-1.11/src/runtime/malloc.go:748 +0xd0 fp=0xc76d64 sp=0xc76d3c pc=0x1b504
runtime.mallocgc(0x20, 0x249320, 0x1, 0x3cb000)
	/usr/lib/go-1.11/src/runtime/malloc.go:903 +0x880 fp=0xc76db8 sp=0xc76d64 pc=0x1bf7c
runtime.newobject(0x249320, 0x0)
	/usr/lib/go-1.11/src/runtime/malloc.go:1032 +0x4c fp=0xc76dcc sp=0xc76db8 pc=0x1c3d8
runtime.makemap_small(0x30)
	/usr/lib/go-1.11/src/runtime/map.go:288 +0x40 fp=0xc76dd8 sp=0xc76dcc pc=0x1d2ec
pack.ag/amqp.linkProperty.func1(0x53fc270, 0x0, 0x0)
	/home/okiengg/go/src/pack.ag/amqp/client.go:1384 +0xe4 fp=0xc76e00 sp=0xc76dd8 pc=0x1eac80
pack.ag/amqp.newLink(0xc68230, 0x0, 0xc76f94, 0x2, 0x2, 0x265f50, 0xc76e64, 0xf9798)
	/home/okiengg/go/src/pack.ag/amqp/client.go:954 +0x160 fp=0xc76e2c sp=0xc76e00 pc=0x1bdd18
pack.ag/amqp.attachLink(0xc68230, 0x0, 0xc76f94, 0x2, 0x2, 0x53e0228, 0x538bfc0, 0x2579e2)
	/home/okiengg/go/src/pack.ag/amqp/client.go:834 +0x60 fp=0xc76f20 sp=0xc76e2c pc=0x1bd228
pack.ag/amqp.(*Session).NewSender(0xc68230, 0xc76f94, 0x2, 0x2, 0x538bfc0, 0x53fe180, 0x53e0220)
	/home/okiengg/go/src/pack.ag/amqp/client.go:442 +0x58 fp=0xc76f48 sp=0xc76f20 pc=0x1bb290
cfxadapter.Amqpserversend()
	/home/okiengg/go/src/cfxadapter/amqpsend.go:49 +0x224 fp=0xc76fec sp=0xc76f48 pc=0x1f09a8
runtime.goexit()
	/usr/lib/go-1.11/src/runtime/asm_mipsx.s:660 +0x4 fp=0xc76fec sp=0xc76fec pc=0x76064
created by main.main
	/home/okiengg/goexample/CVMessages/serial.go:83 +0x1c4

goroutine 1 [syscall]:
syscall.Syscall(0xfa3, 0x5, 0x53ea800, 0x800, 0xc35d20, 0x1, 0xc8424)
	/usr/lib/go-1.11/src/syscall/asm_linux_mipsx.s:17 +0x10
syscall.read(0x5, 0x53ea800, 0x800, 0x800, 0xc35d01, 0x0, 0x0)
	/usr/lib/go-1.11/src/syscall/zsyscall_linux_mipsle.go:732 +0x60
syscall.Read(0x5, 0x53ea800, 0x800, 0x800, 0x0, 0x77ee5000, 0x0)
	/usr/lib/go-1.11/src/syscall/syscall_unix.go:172 +0x54
internal/poll.(*FD).Read(0xc0e800, 0x53ea800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/internal/poll/fd_unix.go:165 +0x120
os.(*File).read(0xc0c530, 0x53ea800, 0x800, 0x800, 0x18, 0x53cc35a, 0x2)
	/usr/lib/go-1.11/src/os/file_unix.go:249 +0x5c
os.(*File).Read(0xc0c530, 0x53ea800, 0x800, 0x800, 0x800, 0x800, 0x2)
	/usr/lib/go-1.11/src/os/file.go:108 +0x6c
main.main()
	/home/okiengg/goexample/CVMessages/serial.go:118 +0x1a94

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x6fd89fc0, 0x72, 0xc9120)
	/usr/lib/go-1.11/src/runtime/netpoll.go:173 +0x60
internal/poll.(*pollDesc).wait(0xc68064, 0x72, 0xffffff00, 0x296420, 0x3b0064)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:85 +0xc4
internal/poll.(*pollDesc).waitRead(0xc68064, 0xcc2000, 0x13a0, 0x13a0)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:90 +0x4c
internal/poll.(*FD).Read(0xc68050, 0xcc2000, 0x13a0, 0x13a0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/internal/poll/fd_unix.go:169 +0x190
net.(*netFD).Read(0xc68050, 0xcc2000, 0x13a0, 0x13a0, 0x4, 0x0, 0x0)
	/usr/lib/go-1.11/src/net/fd_unix.go:202 +0x58
net.(*conn).Read(0xc0c520, 0xcc2000, 0x13a0, 0x13a0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/net/net.go:177 +0x70
main.runtcp()
	/home/okiengg/goexample/CVMessages/serial.go:614 +0xc0
created by main.main
	/home/okiengg/goexample/CVMessages/serial.go:86 +0x1dc

goroutine 11 [IO wait]:
internal/poll.runtime_pollWait(0x6fd89e40, 0x72, 0xc9120)
	/usr/lib/go-1.11/src/runtime/netpoll.go:173 +0x60
internal/poll.(*pollDesc).wait(0xc681f4, 0x72, 0xffffff00, 0x296420, 0x3b0064)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:85 +0xc4
internal/poll.(*pollDesc).waitRead(0xc681f4, 0xcc0400, 0x200, 0x200)
	/usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:90 +0x4c
internal/poll.(*FD).Read(0xc681e0, 0xcc0400, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/internal/poll/fd_unix.go:169 +0x190
net.(*netFD).Read(0xc681e0, 0xcc0400, 0x200, 0x200, 0xce3bdb89, 0xbef89005, 0x71cfd28d)
	/usr/lib/go-1.11/src/net/fd_unix.go:202 +0x58
net.(*conn).Read(0xc0c5d8, 0xcc0400, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/go-1.11/src/net/net.go:177 +0x70
pack.ag/amqp.(*buffer).readFromOnce(0xc77ef4, 0x6fd8a090, 0xc0c5d8, 0x6fd8a090, 0xc0c5d8)
	/home/okiengg/go/src/pack.ag/amqp/buffer.go:102 +0x98
pack.ag/amqp.(*conn).connReader(0xc9a000)
	/home/okiengg/go/src/pack.ag/amqp/conn.go:449 +0x78c
created by pack.ag/amqp.(*conn).start
	/home/okiengg/go/src/pack.ag/amqp/conn.go:257 +0x50

goroutine 12 [select]:
pack.ag/amqp.(*conn).mux(0xc9a000)
	/home/okiengg/go/src/pack.ag/amqp/conn.go:349 +0x440
created by pack.ag/amqp.(*conn).start
	/home/okiengg/go/src/pack.ag/amqp/conn.go:272 +0x108

goroutine 13 [select]:
pack.ag/amqp.(*conn).connWriter(0xc9a000)
	/home/okiengg/go/src/pack.ag/amqp/conn.go:574 +0x178
created by pack.ag/amqp.(*conn).start
	/home/okiengg/go/src/pack.ag/amqp/conn.go:273 +0x12c

goroutine 14 [select]:
pack.ag/amqp.(*Session).mux(0xc68230, 0xc4c1e0)
	/home/okiengg/go/src/pack.ag/amqp/client.go:478 +0x5c4
created by pack.ag/amqp.(*Client).NewSession
	/home/okiengg/go/src/pack.ag/amqp/client.go:154 +0x3a8

goroutine 15 [select, 27 minutes]:
pack.ag/amqp.(*link).mux(0xc7c340)
	/home/okiengg/go/src/pack.ag/amqp/client.go:991 +0x1b4
created by pack.ag/amqp.attachLink
	/home/okiengg/go/src/pack.ag/amqp/client.go:937 +0x4f4

goroutine 16 [select, 27 minutes]:
pack.ag/amqp.(*link).mux(0xc7c410)
	/home/okiengg/go/src/pack.ag/amqp/client.go:991 +0x1b4
created by pack.ag/amqp.attachLink
	/home/okiengg/go/src/pack.ag/amqp/client.go:937 +0x4f4

goroutine 17 [select, 27 minutes]:
pack.ag/amqp.(*link).mux(0xc7c4e0)
	/home/okiengg/go/src/pack.ag/amqp/client.go:991 +0x1b4
created by pack.ag/amqp.attachLink
	/home/okiengg/go/src/pack.ag/amqp/client.go:937 +0x4f4

goroutine 18 [select, 27 minutes]:
pack.ag/amqp.(*link).mux(0xc7c5b0)
	/home/okiengg/go/src/pack.ag/amqp/client.go:991 +0x1b4
created by pack.ag/amqp.attachLink
	/home/okiengg/go/src/pack.ag/amqp/client.go:937 +0x4f4

goroutine 19 [select, 27 minutes]:
pack.ag/amqp.(*link).mux(0xc7c680)
	/home/okiengg/go/src/pack.ag/amqp/client.go:991 +0x1b4
created by pack.ag/amqp.attachLink
	/home/okiengg/go/src/pack.ag/amqp/client.go:937 +0x4f4
`

**Comment by vcabbage** [comment]
Thank you!

I see 5 `link.mux` goroutines, which would imply 5 concurrently opens `Senders` and/or `Receiver`s. Does that sound right for the application?

I _think_ it's running out of memory when trying to create a 6th link. Does the device have limited memory? (Probably a silly question since you already said it's an embedded device.)

I don't think Go provides a mechanism to recover from this sort of panic. If you don't need all the links open concurrently you may be able to save some memory by closing them.

**Comment by vinithadinesh** [comment]
Thank you for providing the lead. Looks like it is happening due to the connection leak which exhausts the limited on-board memory. I will check if closing the links will help.

**Comment by vinithadinesh** [comment]
Thank you. The system does not crash now. The problem was caused due to too many open connections and not closing the unused child processes correctly.

**Comment by vcabbage** [comment]
Glad you got it sorted out :+1:
