### ISSUE TITLE
Question regarding the settle modes to allow delayed message acknowledgement

### ISSUE THREAD

**Issue by talmdal** [vcabbage/amqp#153]
I apologize in advance if this has been asked before. I've been struggling with this for the last two weeks and pulling out what little hair I have left :-/

I'm struggling with the link options that would allow me to receive an incoming message from an Azure IoT Hub (direct method invocation), process the message, accept or reject the incoming request based on the results of the message processing, and then send the response.

What tends to happen is the incoming message is already settled and then the send disposition just waits (client.go line 1833)

It's probably my understanding of things, but I can't get the right combination of Sender/Receive settle settings that allow this processing.

SenderLink Settings
`
	amqp.LinkProperty("com.microsoft:api-version", azuredevicesdk.APIVersion),
 	amqp.LinkProperty("com.microsoft:channel-correlation-id", correlationID),
 	amqp.LinkTargetAddress(dest),
`
ReceiverLink Settings
`
	amqp.LinkProperty("com.microsoft:api-version", azuredevicesdk.APIVersion),
	amqp.LinkProperty("com.microsoft:channel-correlation-id", correlationID),
	amqp.LinkSourceAddress(dest),
	amqp.LinkSenderSettle(amqp.ModeUnsettled),
	amqp.LinkReceiverSettle(amqp.ModeSecond),
`
Any insights or examples that you may be aware of to point me in the right direction would be greatly appreciated.

Thanks

**Comment by devigned** [comment]
Hi @talmdal, if the incoming message is already settled, there is no reason to send a disposition.

What is happening with the configuration above is that you are saying the receiver will wait for an ack on the disposition. This never comes, so the receiver waits indefinitely.

I believe if you set receiver settle mode to first, the receiver will assume the message sent to it will be settled and not try to send a disposition. 

I think that's right, but I mix these up from time to time.

As an aside, have you tried using the [event hub library](https://github.com/Azure/azure-event-hubs-go) to connect to Azure IoT? I think this should just work. If not, open an issue and we'll get it fixed.

**Comment by vcabbage** [comment]
Thanks @devigned! Not being familiar with IoT Hubs, does it support sending messages unsettled to the receiver? Sounds like @talmdal is looking for that behavior.

I should look into the hanging. The client should know which mode was negotiated and act appropriately. Or perhaps provide an error if the requested mode wasn't negotiated. I have run across brokers that simply echo back the mode even if they don't support it though (it wasn't a Microsoft broker).

**Comment by talmdal** [comment]
Thanks guys for the quick response. I had used the Azure Java sample programs and SDK as the model to understand the message flow. (which receives, processes, acknowledges and sends the result) 

I have tried setting the mode to first and then the go client doesn't hang, but the request in the portal times-out. I had seen this behavour in the Java SDK, when I took a while to send the disposition.

So I'm not sure I have the link settings right.

@devigned I'll take a look at using the event hub library. I had seen it, but didn't think I could use it
Thanks again for your input

**Comment by devigned** [comment]
@talmdal I'll look into what's going on between the portal and client lib, and report back. I should be able to get to it today.

**Comment by talmdal** [comment]
@devigned: thanks I appreciate it.  as an aside, sending device-2-cloud messages, receiving cloud-2-device, updating the twin properties and receiving twin updates all work. So I'm pretty sure, it's the "idiot" behind this keyboard that is the problem

**Comment by devigned** [comment]
@talmdal no worries :). This stuff is complicated! 

Unfortunately, I ran out of time to try this out today. I'll update tomorrow.

**Comment by vcabbage** [comment]
@talmdal It seems I didn't read your original post thoroughly enough, my apologies. So it's hanging at line 1833 as seen here?
https://github.com/vcabbage/amqp/blob/d48c91ecba2ea50cd732db309a13cbbc2a25262b/client.go#L1832-L1834

That would be unexpected since that path shouldn't be taken unless batching is enabled. What version are you using? Batching was enabled by default until 0.9.0.

**Comment by talmdal** [comment]
I'm using v0.10.3
It takes the else branch and then waits 11 lines later at 1845:
```
    return <-wait
```

**Comment by talmdal** [comment]
@vcabbage, It looks like the incoming message is being settled on line 1135 (client.go). 

I'm probably doing something wrong with the link options that are causing the receiver settle modes to be negotiated into an inconsistent state so the sender is settling it and the client is expecting to have acknowledge the message.

**Comment by vcabbage** [comment]
If the received message is already settled it shouldn't try to send a disposition due to:
https://github.com/vcabbage/amqp/blob/d48c91ecba2ea50cd732db309a13cbbc2a25262b/types.go#L1812-L1814

Say, are you using `msg.Release()`? I see I have a really silly bug in the logic. It should be `!m.shouldSendDisposition()`
https://github.com/vcabbage/amqp/blob/d48c91ecba2ea50cd732db309a13cbbc2a25262b/types.go#L1773-L1780

I'll get that fixed shortly.

**Comment by talmdal** [comment]
No I'm using Accept(). 

I'm using the following settle options when I create the receiver options:
``` go
amqp.LinkSenderSettle(amqp.ModeUnsettled),
amqp.LinkReceiverSettle(amqp.ModeSecond),
```
I think there are two problems:
1. The first is my understanding of the interaction between the Azure IoT Hub that the received request needs to be manually acknowledged, based on the flow I observed in the Java IoT SDK, which could be flawed.  It's based on the assumption that the flow shouldn't change based the client (they use qpid java client)
2. The second is because I have set the receiver settle mode to ModeSecond, it effectively ignores that the message is settled (on line 1813 !m.settled is false, but the 2nd half will return true if the receiver is mode is modeSecond)

Not sure if this is possible or where it would be appropriate, but getting a warning that the settle modes are inconsistent in this case... Or, should the || on line 1813 be a &&

Tim

**Comment by vcabbage** [comment]
> 2\. The second is because I have set the receiver settle mode to ModeSecond, it effectively ignores that the message is settled (on line 1813 !m.settled is false, but the 2nd half will return true if the receiver is mode is modeSecond)

Oh yes, you're right. Thanks for pointing that out :)

> Not sure if this is possible or where it would be appropriate, but getting a warning that the settle modes are inconsistent in this case... Or, should the || on line 1813 be a &&

I'm starting to think it should be an error if the server returns settlement modes different from what you requested. If there is a use case where one needs to allow that, it could be controlled via an additional link option.

`&&` may be the correct logic there. I'll need to dig into it a little to verify. `ModeSecond` has always been a bit tricky in my mind.

So we can confirm what exactly is happening, would you be able to build with `-tags debug` and provide the output (https://github.com/vcabbage/amqp/blob/master/CONTRIBUTING.md#logging)?

**Comment by talmdal** [comment]
Sure, I can do that

**Comment by talmdal** [comment]
I edited the file to add a descriptive line before the direct method request entries. From what I can see, is the negotiated settle modes completely ignore the requested modes. 

I just had an off the wall thought. I have 3 "channels" that I want to have bi-directional conversations on. I only have one session that is the "parent" of each of the link pairs. Could this be cause the problem and should I have a separate session for each one?

Hope this helps.
[trace_level9.txt](https://github.com/vcabbage/amqp/files/2895877/trace_level9.txt)

**Comment by vcabbage** [comment]
Agreed, the server is responding back with `SenderSettleMode: settled, ReceiverSettleMode: first` to your `SenderSettleMode: unsettled, ReceiverSettleMode: second`.

For sender settle mode the spec says:
> When set at the receiver this indicates the desired value for the settlement mode at the sender. When set at the sender this indicates the actual settlement mode in use. The sender SHOULD respect the receiver's desired settlement mode if the receiver initiates the attach exchange and the sender supports the desired mode. 

For receiver settle mode:
> When set at the sender this indicates the desired value for the settlement mode at the receiver. When set at the receiver this indicates the actual settlement mode in use. The receiver SHOULD respect the sender's desired settlement mode if the sender initiates the attach exchange and the receiver supports the desired mode.

http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#type-attach

So the behavior is certainly within spec for sender mode. Whereas it might not be for the receiver mode. Not all brokers support all modes in all situations though, that may be what's happening here. @devigned, do you have any thoughts on this?

As for this library, I still think the correct behavior is to return an error on mistmatch. Currently it doesn't look at the server's receiver settle mode at all, which explains the hangs you've experienced.

> I just had an off the wall thought. I have 3 "channels" that I want to have bi-directional conversations on. I only have one session that is the "parent" of each of the link pairs. Could this be cause the problem and should I have a separate session for each one?

Each broker does seem to have their idiosyncrasies. My guess is it's just not supported for that link address (not sure on the IoT Hub terminology for that link).

**Comment by talmdal** [comment]
Thanks for the quick response, 
I might give it a try to create a session for each conversation to see if I can rule out any overlap on different settings.

I think you are right, in providing some feedback to the application when there is a settlement mismatch.  I've always said if you want to find all the corner case in software give it to the user (in this case that's me) and we will find ways to break it 😉

**Comment by devigned** [comment]
@shubha or @clemensv any thoughts on the Event Hubs interpretation of this issue?

**Comment by vcabbage** [comment]
> I've always said if you want to find all the corner case in software give it to the user (in this case that's me) and we will find ways to break it

Bug reports like this are very much appreciated! I started writing this library because I wanted to see if I could avoid C bindings and it sounded like fun. It pretty much only worked for my limited use case initially (I'm using a rather generous definition of "worked"). It would still be that way if it weren't for all the contributions; including bug reports, discussions, and code.

**Comment by talmdal** [comment]
An update from playing this weekend.

I tried to create 3 sessions, one per conversation, but that didn't help, but I noticed was that when I created the third session, the second session closed.  End of that trial.

I did notice a different behavior if I didn't explicitly set the settle modes on the sender link that that I was trying to send the response on. Without them set, the message was transferred and the remote responded with settled and accepted:

> 08:02:59.403202 TX(link): Transfer{Handle: 4, DeliveryID: 3, DeliveryTag: "\x00\x00\x00\x00\x00\x00\x00\x00", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 196}
08:02:59.403230 TX(Session): Transfer{Handle: 4, DeliveryID: 3, DeliveryTag: "\x00\x00\x00\x00\x00\x00\x00\x00", MessageFormat: 0, Settled: false, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 196}
08:02:59.440661 RX(Session): Disposition{Role: Receiver, First: 3, Last: <nil>, Settled: true, State: Accepted, Batchable: false}
08:02:59.440714 RX: Disposition{Role: Receiver, First: 3, Last: <nil>, Settled: true, State: Accepted, Batchable: false}

Whereas, if I set settle mode to sender: Settled and receiver: First, I see no response from the remote:

> 07:57:58.316303 TX(link): Transfer{Handle: 4, DeliveryID: 3, DeliveryTag: "\x00\x00\x00\x00\x00\x00\x00\x00", MessageFormat: 0, Settled: true, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 196}
07:57:58.316328 TX(Session): Transfer{Handle: 4, DeliveryID: 3, DeliveryTag: "\x00\x00\x00\x00\x00\x00\x00\x00", MessageFormat: 0, Settled: true, More: false, ReceiverSettleMode: <nil>, State: <nil>, Resume: false, Aborted: false, Batchable: false, Payload [size]: 196}

Interesting, but not sure that it impacts the problem at hand, just reaffirms something I learned along time ago... always be explicit when setting options. 😉 

I have been unable to find any details on what the amqp message flow on the IoTHub side of things is in order understand why the negotiation between the remote and my program is failing when trying to set the settle modes.

**Comment by talmdal** [comment]
I did some more digging and I think I might be chasing a ghosts here.  I was able to dump the message when it arrives in the Java SDK client I've been using as a message flow model, and was surprised to find that it had been settled on the remote.  Then I spent sometime following the acknowledgement logic and found that it recognizes the remote has settled the message and doesn't try to send a disposition, just does some local message handling cleanup

I changed the || to a && in shouldSendDisposition locally and I didn't get the "hang" that I was seeing.

At this point, I think we can call this issue resolved and you can close it unless you want to keep it open  to address the error when the sender settle mode don't match expected. 

Thanks for everyones input

**Comment by vcabbage** [comment]
Thanks for the update! I'm going to leave this open at least until I'm able to determine the proper way to handle this. I think a library blindly accepting the settlement mode when the user requested something different is at best surprising but could also have more serious ramifications if the application logic expects a particular mode.

I found another reference to the settlement modes here: https://issues.oasis-open.org/browse/AMQP-37
> Clarify the text to make clearer that the initiator is getting the chance to choose the settlement policy of its peer. For example a client can choose the policy it wants at the broker, and if the broker supports the policy it SHOULD agree to the client's request.

This make's me think the intention is to allow the client to request the modes but the broker gets to decide. The spec seems less clear on this, to me at least.

My understanding of settle modes is that sender and receiver settlement states are independent. The `settled bool` on the message corresponds only to the sender's settlement state. If that's correct, the `||` in `shouldSendDispostion` isn't necessarily the problem. Rather it goes back to the link not being updated with the receiver settle mode from the broker's attach frame. If it were the second part of the expression would also evaluate to false and it would not attempt to send the disposition.

Thanks again for taking the time to work though this and reporting your findings, I really appreciate it!

**Comment by talmdal** [comment]
After reading the spec as well, I think you are on the right track.  It looks like it's not really an error condition, as it seems to be a normal course of events for the sender to potentially ignore the request from the receiver as it does say "SHOULD" not "MUST". From my understanding, the "|| ..." is just not needed as if the received message is already settled, then there is really no option, but accept that.

Thanks again

**Comment by vcabbage** [comment]
I've merged the error on mismatch logic and tagged it as v0.11.0.

I'm going to go ahead and close this issue. Please feel free to reopen if I've missed anything.
