### ISSUE TITLE
Enable durable option for target

### ISSUE THREAD

**Issue by inosus** [vcabbage/amqp#156]
Currently we are successfully using the library with rabbitmq and it's AMQP 1.0 plugin.
Issue #133 talked about adding an option for durability. This was then implemented for the source https://github.com/vcabbage/amqp/issues/133#issuecomment-431618107

The same option for target would be very welcome. 

Reasoning: 
The same precondition_failed issue (see below) that was solved with https://github.com/vcabbage/amqp/pull/137 also exists with the target.

*Error{Condition: amqp:precondition-failed, Description: PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'processed' in vhost '/': received 'false' but current is 'true', Info: map[]}

If need be i'm willing to add the new option.
I think adding a LinkTargetDurability function should do it unless a different approach is required.

**Comment by vcabbage** [comment]
Hi @inosus, thanks for opening this issue!

This seems like a reasonable addition. You're on the right track, it should be nearly identical to the `LinkSourceDurability` implementation. A PR would be very welcome!

**Comment by carlosmaersk** [comment]
@vcabbage hi! we have been using your project and noticed this open issue, which is something we are in need of, I created #189 to hopefully help with this.

**Comment by vcabbage** [comment]
@carlosmaersk Thanks! The addition has been tagged as v0.12.4.
