### ISSUE TITLE
Fails to connect to QMF Events exchange

### ISSUE THREAD

**Issue by AkaFletch** [vcabbage/amqp#158]
Apache's Qpid C++ server uses amqp version 1 and provides a exchange which will send messages for every event through the broker on exchange "qmf.default.topic/agent.ind.event.org_apache_qpid_broker.#" 
However this library fails to connect to this address because it believes it does not exist. Though it manages to connect to "qmf.default.topic" and receive messages.

Apaches own python and C++ amqp clients happily manage to connect to this exchange and receive messages. Is this unintended behaviour within this library? 

My environment:
- Centos 7
- Go 1.12
- Qpid cpp server 1.39.0
- qpid-proton-c 0.26.0

**Comment by vcabbage** [comment]
Hi @AkaFletch! Can you post the options you're using to connect and the error message returned? It may well be a bug in this library but a fair number connection issues like this come down to the broker expecting a specific set of options. If the error isn't very specific, the output when compiled with [`-tags debug`](https://github.com/vcabbage/amqp/blob/master/CONTRIBUTING.md#logging) may reveal what's happening.

Having little familiarity with that broker I may need to try to reproduce it locally later on when I have some time, but getting some of these details in the mean time would be helpful. Thanks!

**Comment by AkaFletch** [comment]
So the broker is running on local host so I'm using 127.0.0.1 as a parameter to amqp.Dial, the error received with -tags debug is:

"09:35:46.907853 TX: Begin{RemoteChannel: 0, NextOutgoingID: 0, IncomingWindow: 100, OutgoingWindow: 100, HandleMax: 4294967295, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
09:35:46.909091 RX: Begin{RemoteChannel: 0, NextOutgoingID: 0, IncomingWindow: 2147483647, OutgoingWindow: 2147483647, HandleMax: 4294967295, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
09:35:46.909218 TX: Attach{Name: svdTa6l-2FISPe7TSuxPaC2ff7xZmKCEo_PIRnFgF7k-P95XM57xzg, Handle: 0, Role: Receiver, SenderSettleMode: <nil>, ReceiverSettleMode: <nil>, Source: source{Address: qmf.default.topic:agent.ind.event.org_apache_qpid_broker.#, Durable: 0, ExpiryPolicy: , Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], DistributionMode: , Filter: map[], DefaultOutcome: <nil>Outcomes: [], Capabilities: []}, Target: <nil>, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 0, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
09:35:46.911793 RX(Session): Attach{Name: svdTa6l-2FISPe7TSuxPaC2ff7xZmKCEo_PIRnFgF7k-P95XM57xzg, Handle: 0, Role: Sender, SenderSettleMode: mixed, ReceiverSettleMode: first, Source: <nil>, Target: source{Address: , Durable: 0, ExpiryPolicy: session-end, Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], Capabilities: []}, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 0, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
09:35:46.911839 RX(Session): Detach{Handle: 0, Closed: true, Error: *Error{Condition: amqp:not-found, Description: Node not found: qmf.default.topic:agent.ind.event.org_apache_qpid_broker.#, Info: map[]}}
09:35:46.911951 RX: Detach{Handle: 0, Closed: true, Error: *Error{Condition: amqp:not-found, Description: Node not found: qmf.default.topic:agent.ind.event.org_apache_qpid_broker.#, Info: map[]}}
09:35:46.911968 TX(Session): Detach{Handle: 0, Closed: true, Error: *Error(nil)}
2019/03/05 09:35:46 Reading message from AMQP:link detached, reason: *Error{Condition: amqp:not-found, Description: Node not found: qmf.default.topic:agent.ind.event.org_apache_qpid_broker.#, Info: map[]}
exit status 1
"

When reading from the qmf.default.topic/agent.ind.event.org_apache_qpid_broker.# exhange with the python reader if I run the code I see the messages for client connect and for a client disconnect, it seems the library is the one disconnecting itself from the exchange as it believes the node does not exsist

**Comment by vcabbage** [comment]
Thanks for the logs :+1: 

The broker is rejecting the link attachment with the `amqp:not-found` error and description `Node not found: qmf.default.topic:agent.ind.event.org_apache_qpid_broker.#`.

From what I can see here it's attempting to attach to the source address `qmf.default.topic:agent.ind.event.org_apache_qpid_broker.#`, should that be `qmf.default.topic/agent.ind.event.org_apache_qpid_broker.#` (with a `/` instead of a `:`)?

**Comment by AkaFletch** [comment]
Hey sorry for the late reply, you're compleatly right it should of used the `/` I was trying different combinations of the broker address in desperation. However changing to use the original broker address `qmf.default.topic/agent.ind.event.org_apache_qpid_broker.#` I'm getting the same error 

> 09:33:50.397320 TX: Begin{RemoteChannel: 0, NextOutgoingID: 0, IncomingWindow: 100, OutgoingWindow: 100, HandleMax: 4294967295, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
09:33:50.398136 RX: Begin{RemoteChannel: 0, NextOutgoingID: 0, IncomingWindow: 2147483647, OutgoingWindow: 2147483647, HandleMax: 4294967295, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
09:33:50.398266 TX: Attach{Name: n28KgFHQw8q4S_VBWWohqBT4txEhPgsdPm1RbVoZRNqapUd9XuwoSA, Handle: 0, Role: Receiver, SenderSettleMode: <nil>, ReceiverSettleMode: <nil>, Source: source{Address: qmf.default.topic/agent.ind.event.org_apache_qpid_broker.#, Durable: 0, ExpiryPolicy: , Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], DistributionMode: , Filter: map[], DefaultOutcome: <nil>Outcomes: [], Capabilities: []}, Target: <nil>, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 0, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
09:33:50.399191 RX(Session): Attach{Name: n28KgFHQw8q4S_VBWWohqBT4txEhPgsdPm1RbVoZRNqapUd9XuwoSA, Handle: 0, Role: Sender, SenderSettleMode: mixed, ReceiverSettleMode: first, Source: <nil>, Target: source{Address: , Durable: 0, ExpiryPolicy: session-end, Timeout: 0, Dynamic: false, DynamicNodeProperties: map[], Capabilities: []}, Unsettled: map[], IncompleteUnsettled: false, InitialDeliveryCount: 0, MaxMessageSize: 0, OfferedCapabilities: [], DesiredCapabilities: [], Properties: map[]}
09:33:50.399235 RX(Session): Detach{Handle: 0, Closed: true, Error: *Error{Condition: amqp:not-found, Description: Node not found: qmf.default.topic/agent.ind.event.org_apache_qpid_broker.#, Info: map[]}}
09:33:50.399309 RX: Detach{Handle: 0, Closed: true, Error: *Error{Condition: amqp:not-found, Description: Node not found: qmf.default.topic/agent.ind.event.org_apache_qpid_broker.#, Info: map[]}}
09:33:50.399323 TX(Session): Detach{Handle: 0, Closed: true, Error: *Error(nil)}
2019/03/07 09:33:50 Reading message from AMQP:link detached, reason: *Error{Condition: amqp:not-found, Description: Node not found: qmf.default.topic/agent.ind.event.org_apache_qpid_broker.#, Info: map[]}
exit status 1

This still seems to be a disconnect from the broker, I'm going to keep trying with auth settings / different addresses. I'll update if I find any settings that seem to make progress.

**Comment by AkaFletch** [comment]
I've managed to finally connect using the proton implementation of qpid, but I thought I'd update here for anyone in the future, turns out the rest of the string after the / is a filter which the python-qpid version would abstract the implementation of for you. I'm fairly sure from a quick search that filters are defined in this library too. So the final solution was to connect with the address qmf.default.topic and then use a apache.org:legacy-amqp-topic-binding:string filter with the value agent.ind.event.org_apache_qpid_broker.#

Cheers for your help @vcabbage, You gave me some good directions to look into, especially with the `-tags debug` option

**Comment by vcabbage** [comment]
I'm glad to hear you got it sorted out and the update is appreciated!

Do you happen to have a link to the relevant documentation? No worries if not, just thinking it might be useful if someone else runs into a similar issue.

**Comment by AkaFletch** [comment]
Absolutely, here's the AMQP specification which defines filters: [https://svn.apache.org/repos/asf/qpid/trunk/qpid/specs/apache-filters.xml#section-legacy-amqp](url)

From there I used this example to see a basic implementation of the filters for Qpid-Proton: [https://github.com/apache/qpid-proton/blob/master/go/examples/electron/selected_recv.go](url)

My changes to the above example were to change the AMQP Symbol from `apache.org:selector-filter:string` to `apache.org:legacy-amqp-topic-binding:string` 

Then the value passed into `selectorFilter` was changed to the `agent.ind.event.org_apache_qpid_broker.#` removing it from the end of the broker address. 

To my quick look this library seems to have similar functionality in client.go with LinkSelectorFilter.
