### ISSUE TITLE
pub-sub pattern

### ISSUE THREAD

**Issue by alext234** [vcabbage/amqp#160]
I've gone through godoc but have not found this.
Is there an API for the pub-sub pattern?

**Comment by vcabbage** [comment]
Hi @alext234,

This library is primarily a low-level client for AMQP 1.0. AMQP 1.0 doesn't directly define any semantics such as pub/sub, which is left up to the brokers. Higher level libraries for interacting with specific brokers may provide a pub/sub API. One example is https://github.com/google/go-cloud, where the Azure Pub/Sub implementation uses this library.
