### ISSUE TITLE
Support establishing a new session that is initiated on the remote peer. 

### ISSUE THREAD

**Issue by chirino** [vcabbage/amqp#176]
If the remote amqp peer tries to initiate creating a new session, this client closes out the amqp connection due to this error:

`unexpected frame: &amqp.performBegin{RemoteChannel:0x0, NextOutgoingID:0x0, IncomingWindow:0x64, OutgoingWindow:0x64, HandleMax:0xffffffff, OfferedCapabilities:amqp.multiSymbol(nil), DesiredCapabilities:amqp.multiSymbol(nil), Properties:map[amqp.symbol]interface {}(nil)}`

**Comment by vcabbage** [comment]
This issue got lost in my email, oops. It appears that @alanconway is looking into adding support for this in #177

**Comment by chirino** [comment]
closing as a dup of #177
