### ISSUE TITLE
Best Practices for Sessions

### ISSUE THREAD

**Issue by borlinp** [vcabbage/amqp#180]
We are building a new project with this library.  I see there is a Client, Session, Receiver, and Sender.  What is the best practices for retaining an instance of each of those?  Here are my assumptions from having use AMQP in the past:

- Client would be once per lifetime of the application
- Session - this I am not sure of - Once per lifetime of application?  Once per use?  Once per thread?
- Receiver - once per use/subscription
- Sender - once per use/send

Please help me correct my assumptions so that we use these correctly.  Thanks.

**Comment by vcabbage** [comment]
In my own usage I create one client, session, and receiver. If an error occurs, such as a network problem, I close and re-create all three.

I'm afraid I don't have any general advice as far as performance goes. All sends and receives are multiplexed over the same client/connection, so it's possible that multiple clients could provide a benefit. I haven't done any testing in this area.

Sorry I'm unable to provide more concrete advice.

**Comment by borlinp** [comment]
If we discover a good pattern, we'll let you know.  For now, we are going to keep one client for the life of the application, and create the other 3 on demand.  Thanks.
