### ISSUE TITLE
IdleTimeout make i/o timeout bug when client only have a receiver session.

### ISSUE THREAD

**Issue by hanjm** [vcabbage/amqp#181]
IdleTimeout default is 1 min, if a queue no message in 1 min and client only have one receiver session, no sender session, the client will fail on i/o timeout.

run demo output:
2019/10/31 12:58:36 start Receive
2019/10/31 12:59:36 Reading message from AMQP:read tcp 127.0.0.1:58524->127.0.0.1:5672: i/o timeout
2019/10/31 12:59:36 Reading message from AMQP:read tcp 127.0.0.1:58524->127.0.0.1:5672: i/o timeout
2019/10/31 12:59:36 Reading message from AMQP:read tcp 127.0.0.1:58524->127.0.0.1:5672: i/o timeout
2019/10/31 12:59:36 Reading message from AMQP:read tcp 127.0.0.1:58524->127.0.0.1:5672: i/o timeout
2019/10/31 12:59:36 Reading message from AMQP:read tcp 127.0.0.1:58524->127.0.0.1:5672: i/o timeout
2019/10/31 12:59:36 Reading message from AMQP:read tcp 127.0.0.1:58524->127.0.0.1:5672: i/o timeout
2019/10/31 12:59:36 Reading message from AMQP:read tcp 127.0.0.1:58524->127.0.0.1:5672: i/o timeout
2019/10/31 12:59:36 Reading message from AMQP:read tcp 127.0.0.1:58524->127.0.0.1:5672: i/o timeout
2019/10/31 12:59:36 Reading message from AMQP:read tcp 127.0.0.1:58524->127.0.0.1:5672: i/o timeout
2019/10/31 12:59:36 Reading message from AMQP:read tcp 127.0.0.1:58524->127.0.0.1:5672: i/o timeout

Process finished with exit code 0
```go
package main

import (
	"context"
	"fmt"
	"log"
	"sync"
	"time"

	"pack.ag/amqp"
)

func main() {
	// Create client
	client, err := amqp.Dial("amqp://127.0.0.1",
		amqp.ConnSASLPlain("system", "manager"),
		amqp.ConnConnectTimeout(time.Second*10),
		//amqp.ConnIdleTimeout(0),
	)
	if err != nil {
		log.Fatal("Dialing AMQP server:", err)
	}
	defer client.Close()

	// Open a session
	session, err := client.NewSession()
	if err != nil {
		log.Fatal("Creating AMQP session:", err)
	}

	ctx := context.Background()

	// Send a message
	// IdleTimeout default is 1 min, if a queue no message in 1 min and client only have one receiver session, no sender session, the client will fail on i/o timeout. 
	//{
	//	// Create a sender
	//	sender, err := session.NewSender(
	//		amqp.LinkTargetAddress("/queue-name"),
	//	)
	//	if err != nil {
	//		log.Fatal("Creating sender link:", err)
	//	}
	//
	//	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	//
	//	// Send message
	//	err = sender.Send(ctx, amqp.NewMessage([]byte("Hello!")))
	//	if err != nil {
	//		log.Fatal("Sending message:", err)
	//	}
	//
	//	sender.Close(ctx)
	//	cancel()
	//}

	// Continuously read messages
	{
		// Create a receiver
		receiver, err := session.NewReceiver(
			amqp.LinkSourceAddress("/queue-name"),
			amqp.LinkCredit(1),
		)
		if err != nil {
			log.Fatal("Creating receiver link:", err)
		}
		defer func() {
			ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
			receiver.Close(ctx)
			cancel()
		}()

		log.Printf("start Receive")
		ctx := context.Background()
		var wg sync.WaitGroup
		for i := 0; i < 10; i++ {
			wg.Add(1)
			go func() {
				defer wg.Done()
				for {
					// Receive next message
					msg, err := receiver.Receive(ctx)
					if err != nil {
						log.Print("Reading message from AMQP:", err)
						return
					}

					time.Sleep(time.Second)
					// Accept message
					err = msg.Accept()
					if err != nil {
						log.Print("Accept message from AMQP:", err)
						return
					}

					fmt.Printf("Message received: %s\n", msg.GetData())
				}
			}()
		}
		wg.Wait()
	}
}
```

i think IdleTimeout should not used to set both keepAliveTime and readTimeout.
https://github.com/vcabbage/amqp/blob/master/conn.go#L457
https://github.com/vcabbage/amqp/blob/master/conn.go#L852
https://github.com/vcabbage/amqp/blob/master/conn.go#L570

**Comment by vcabbage** [comment]
Each side of an AMQP connection specifies it's idle timeout. It's up to the peer to send some traffic within the interval. If there are no messages to be sent:

> If a peer needs to satisfy the need to send traffic to prevent idle timeout, and has nothing to send, it MAY send an empty frame, i.e., a frame consisting solely of a frame header, with no frame body. [...]
http://docs.oasis-open.org/amqp/core/v1.0/cos01/amqp-core-transport-v1.0-cos01.html#doc-doc-idle-time-out
