### ISSUE TITLE
Respect auth credentials in the URL

### ISSUE THREAD

**Issue by amenzhinsky** [vcabbage/amqp#20]
When dialing an URL we should handle the username/password segment as SASL credentials e.g. `amqp://user:pass@amqp.example.org`

**Comment by vcabbage** [comment]
Is this part of the spec or an established practice in other client libraries?

**Comment by amenzhinsky** [comment]
The second. 
I've seen this in qpid and other drivers, e.g. amqp10 for nodejs.

**Comment by vcabbage** [comment]
I'm not opposed if it's legitimately useful and isn't going to encourage bad security practices. I'm not certain either way in regards to the security part, so I'll look into that.

**Comment by amenzhinsky** [comment]
Sure take your time.
I found it useful dealing with redirects when error body contains full url address where you're being redirected.

P.S. SASL creds are plain text so it's not secure either way if you're sending them over unencrypted connection.

**Comment by vcabbage** [comment]
This seems reasonable considering the usability improvement with redirects.

The `ConnSASLPlain` option notes that it should only be used on encrypted sessions. I suppose the library can't/shouldn't protect folks from every possible misuse.
