### ISSUE TITLE
Unmarshaling non-scalar values like arrays, lists, maps, etc.

### ISSUE THREAD

**Issue by amenzhinsky** [vcabbage/amqp#21]
Right now it's failing to unmarshal  this kind of messages, probably it's needed to review how encoding-decoding is done from go to amqp data types (and visa versa).

**Comment by vcabbage** [comment]
I'm working on better type support and cleaning up the encoding/decoding code in the `more-types` branch (it's a working branch; may be rebased, etc). It adds support for arrays (of most types), lists, maps, and floating pointer numbers.

It should be almost ready to merge, I need to do some integration testing with it.
