### ISSUE TITLE
Claims-based Security Support

### ISSUE THREAD

**Issue by devigned** [vcabbage/amqp#24]
[AMQP Claims-based Security](https://www.oasis-open.org/committees/document.php?document_id=50506&wg_abbrev=amqp): Defines a layered protocol to authenticate AMQP clients using security tokens (working draft).

This would enable a consumer of the library to provide a set of claims for fine grained access control, a token with a TTL and a token type to negotiate a connection via SASL.

This is based on the [AMQP management specification](https://www.oasis-open.org/committees/document.php?document_id=54441&wg_abbrev=amqp), also in working draft.

One example implementor is [Azure Service Bus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-protocol-guide#advanced-service-bus-capabilities) using either SAS or JWT tokens. A good example of this is [AMQPNetLite CBS example](https://github.com/Azure/amqpnetlite/blob/master/Examples/ServiceBus/Scenarios/CbsAsyncExample.cs).

**Comment by vcabbage** [comment]
Is there anything in particular the library needs to support for this? I did a cursory review of the documents and it appears that support is built on top of the message application-properties and value payload.

**Comment by devigned** [comment]
Perhaps, I missed something. I’ll give it a go today and respond.

**Comment by devigned** [comment]
```go
func newWithServicePrincipalToken(spToken *adal.ServicePrincipalToken, namespace string, env azure.Environment) (*serviceBus, error) {
	host := fmt.Sprintf("amqps://%s.%s", namespace, "servicebus.windows.net")
	fmt.Println(host)
	client, err := amqp.Dial(host, amqp.ConnSASLAnonymous(), amqp.ConnMaxSessions(65535))
	if err != nil {
		return nil, err
	}

	authSession, err := client.NewSession()
	if err != nil {
		return nil, err
	}

	authSender, err := authSession.NewSender(amqp.LinkTargetAddress("$cbs"))
	if err != nil {
		return nil, err
	}

	cbsClientAddress := "cbs-client-reply-to"
	authReceiver, err := authSession.NewReceiver(
		amqp.LinkSourceAddress("$cbs"),
		amqp.LinkTargetAddress(cbsClientAddress))
	if err != nil {
		return nil, err
	}

	msg := &amqp.Message{
		Value: spToken.AccessToken,
		Properties: &amqp.MessageProperties{
			MessageID: "1",
			ReplyTo:   cbsClientAddress,
		},
		ApplicationProperties: map[string]interface{}{
			"operation": "put-token",
			"type":      "servicebus.windows.net:jwt",
			"name":      host,
		},
	}
	err = authSender.Send(context.Background(), msg)
	if err != nil {
		return nil, err
	}

	response, err := authReceiver.Receive(context.Background())
	if err != nil {
		return nil, err
	}

	if statusCode, ok := response.ApplicationProperties["status-code"].(int32); ok {
		if statusCode == 200 {
			sb := &serviceBus{
				Logger: log.New(),
				client: client,
			}
			sb.Logger.SetLevel(log.WarnLevel)
			sb.senders = make(map[string]*sender)
			return sb, nil
		}
		if statusDescription, ok := response.ApplicationProperties["status-description"].(string); ok {
			return nil, errors.New(statusDescription)
		} else {
			return nil, fmt.Errorf("auth status code failed with value %d", statusCode)
		}
	}

	return nil, errors.New("auth response was malformed")
}
```

The above gives me back a proper error code from the service. I still have to work out some rough edges, but I think all of the pieces are there to accomplish CBS.

Thanks! I should have looked a bit closer.
