### ISSUE TITLE
Connection Open Properties

### ISSUE THREAD

**Issue by devigned** [vcabbage/amqp#28]
On the open performative, field `properties` provides a nice way to add user-agent and other helpful information. Unfortunately, there is no way to get at this internal map at this point.

1) Would you like to expose configuring this map?
2) If so, would the best way to handle this be a new `ConnOption`?

**Comment by vcabbage** [comment]
Sounds reasonable.

My initial thought would be something like `ConnProperty(key, value string) ConnOption`. This is a bit different than the `String` suffix like on `LinkSourceFilterString` as we discussed in #26. After thinking about that case, I think it makes sense to omit the suffix for options that are usually going to have a string value. I'm assuming that's the case here.

Is there an example in one of the other client libraries of what sort of properties are typically added?

Are consumers of this library likely to want access to the properties from the server's open performative?

**Comment by devigned** [comment]
Here's an example of usage via the Azure SB Java lib using proton-j https://github.com/Azure/azure-event-hubs-java/blob/8d729ac85b12078c2d75f6390c0c6195e41b2f03/azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/amqp/ConnectionHandler.java#L53-L65.

Hmm... I'm not sure if consumers would be interested in the server's open performative.

**Comment by vcabbage** [comment]
It looks like all values in the example are strings, so `ConnProperty(key, value string) ConnOption` should suffice for now. I'd be happy to accept a PR adding this functionality.

I'll defer allowing the consumers of the library access to the server's properties until someone asks for it.

**Comment by devigned** [comment]
Cool. I'll add a PR in the next day or so.
