### ISSUE TITLE
LinkProperties other than string

### ISSUE THREAD

**Issue by devigned** [vcabbage/amqp#44]
I was hoping that properties could stay string values, but it appears strings will not suffice. This has come up due to epoch functionality described in #43. Epoch values can _only_ be longs. 

As discussed in #28 and #26, you didn't want to expose `interface{}` as the value of a property, so we landed on exposing only string. Now that there is real need to set values other than string, how would you like to see LinkProperties implemented?

**Comment by vcabbage** [comment]
My thinking was to create additional options like `LinkPropertyInt64(key string, value int64) LinkOption` as needed. I don't feel a strong need to create versions for each type up front, but we should probably keep parity between `LinkProperty` and `ConnProperty` options.

**Comment by devigned** [comment]
Sounds good. I'll supply a PR.
